**히든 레이어**
- 입력 레이어와 출력 레이어 사이의 층.
- 많이 쌓일수록, 결과가 더 정확해짐.
- 활성화 함수로는 ```swish```를 사용

**히든 레이어 - 보스턴 집값 예측**

In [1]:
# 라이브러리 사용

import tensorflow as tf
import pandas as pd

In [2]:
# 1. 과거의 데이터를 준비합니다.

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)


# 독립변수와 종속변수

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [7]:
# 2. 모델의 구조를 만듭니다.

X = tf.keras.layers.Input(shape = [13])
H = tf.keras.layers.Dense(10, activation = 'swish')(X)  # 히든 레이어 생성
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'mse')

In [9]:
model.summary()  # 모델의 구조 확인하는 코드

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [12]:
# 3. 데이터로 모델을 학습(fit)합니다.

model.fit(독립, 종속, epochs = 1000, verbose = 0)
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 20.5313
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 21.9723
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 19.9100
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 21.3459
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 20.3547
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 20.9411
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 21.6283
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 21.4843
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 20.7050
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 21.2105


In [13]:
# 4. 모델을 이용합니다.

print(model.predict(독립[:5]))
print(종속[:5])

[[28.882624]
 [23.391987]
 [29.716093]
 [28.660673]
 [28.235117]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


**히든 레이어 - 아이리스 품종 분류**

In [14]:
import tensorflow as tf
import pandas as pd

In [15]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [20]:
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [21]:
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [42]:
X = tf.keras.layers.Input(shape = [4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)
models = tf.keras.models.Model(X, Y)
models.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [47]:
models.fit(독립, 종속, epochs = 10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3848 - accuracy: 0.9267
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3704 - accuracy: 0.9600
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3610 - accuracy: 0.9333
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3442 - accuracy: 0.9400
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.9600
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.3200 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3103 - accuracy: 0.9533
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.2963 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.2857 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.2806 - accuracy: 0.9600


In [48]:
print(models.predict(독립[:5]))
print(종속[:5])

[[0.9714256  0.02683425 0.00174016]
 [0.9578919  0.03919976 0.00290827]
 [0.9631742  0.03417732 0.00264838]
 [0.9534404  0.04304427 0.00351535]
 [0.97184426 0.02639041 0.00176541]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
